# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  memory_reflection:
    class: MemoryReflectionJob
    queue: default
    schedule: every day at 3am

  consolidate_conversations:
    class: ConsolidateStaleConversationsJob
    schedule: every hour at minute 30

  database_backup:
    class: DatabaseBackupJob
    schedule: every day at 4am

  conversation_initiation:
    class: ConversationInitiationJob
    schedule: every hour at minute 0

  # memory_refinement:
  #   class: MemoryRefinementJob
  #   queue: default
  #   schedule: every monday at 4am

  sync_oura_data:
    class: SyncOuraDataJob
    queue: default
    schedule: every 4 hours
